### ISSUE TITLE
Crash during Minecraft startup

### ISSUE THREAD

**Issue by lospejos** [FrozenBlock/FrozenLib#27]
**Description of the Bug Encountered**

Having mods installed:
```
Loading 362 mods:
	- actuallyunbreaking 1.20-0.1.0
	- additionalstructures 4.2.0
	- advancednetherite 2.0.2-1.20.1
	- adventurez 1.4.18
	- allarrowsinfinityfix 1.4
	- alloy_forgery 2.0.22+1.20
	- ambientsounds unspecified
	- amecs 1.3.9+mc.1.20-pre2
	   \-- amecsapi 1.4.0+mc1.20-pre1
	- amethysttools v1.0_fabric+quilt_mc1.20.0
	- antighost 1.20-fabric0.83.0-1.1.5
	   \-- crowdin-translate 1.4+1.19.3
	- appleskin 2.5.0+mc1.20
	   \-- cloth-config 11.0.99
	        \-- cloth-basic-math 0.6.1
	- architectury 9.1.10
	- areas 5.0
	- armorpointspp 3.1.1
	   \-- fiber 0.23.0-2
	- armorskin 0.2
	- audaki_cart_engine 2.0.5
	- authme 7.0.2+1.20
	- autoclicker-fabric 1.20.1-1.6.2-build.9999
	- autofish 0.9.11
	   \-- cloth-config 11.0.99
	        \-- cloth-basic-math 0.6.1
	- axesareweapons 1.7.0
	- axolotlbuckets 1.2.0
	- axolotlitemfix 1.1.7
	- azure-paxels 1.0.5
	- azurelib 1.0.19
	   \-- com_eliotlash_mclib_mclib 20
	- bclib 3.0.11
	   \-- wunderlib 1.1.5
	- betteradvancements 0.3.2.161
	- betterend 4.0.8
	- betterf3 7.0.1
	- betternether 9.0.8
	- biomemakeover 1.20.1-1.10.2
	   \-- taniwha 1.20.0-5.1.1
	- boatiview 0.0.5
	   \-- cloth-config 11.0.99
	        \-- cloth-basic-math 0.6.1
	- bookshelf 20.0.1
	- bosses_of_mass_destruction 1.7-1.20
	   |-- maelstrom_library 1.6-1.20
	   \-- multipart_entities 1.5-1.20
	- c2me 0.2.0+alpha.10.94
	   |-- c2me-base 0.2.0+alpha.10.94
	   |-- c2me-client-uncapvd 0.2.0+alpha.10.94
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.10.94
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.10.94
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.10.94
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.10.94
	   |-- c2me-notickvd 0.2.0+alpha.10.94
	   |-- c2me-opts-allocs 0.2.0+alpha.10.94
	   |-- c2me-opts-chunk-access 0.2.0+alpha.10.94
	   |-- c2me-opts-chunkio 0.2.0+alpha.10.94
	   |-- c2me-opts-math 0.2.0+alpha.10.94
	   |-- c2me-opts-scheduling 0.2.0+alpha.10.94
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.10.94
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.10.94
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.10.94
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.10.94
	   |-- c2me-server-utils 0.2.0+alpha.10.94
	   |-- c2me-threading-chunkio 0.2.0+alpha.10.94
	   |-- c2me-threading-lighting 0.2.0+alpha.10.94
	   |-- c2me-threading-worldgen 0.2.0+alpha.10.94
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- cardinal-components 5.2.1
	   |-- cardinal-components-base 5.2.1
	   |-- cardinal-components-block 5.2.1
	   |-- cardinal-components-chunk 5.2.1
	   |-- cardinal-components-entity 5.2.1
	   |-- cardinal-components-item 5.2.1
	   |-- cardinal-components-level 5.2.1
	   |-- cardinal-components-scoreboard 5.2.1
	   \-- cardinal-components-world 5.2.1
	- castle_dungeons 4.0.0
	- cateyes 7.3.1
	- cbp 1.0.5.1
	- cherish 1.2.0
	- cherishedworlds 6.1.1+1.20.1
	- clumps 12.0.0.3
	- collective 6.65
	- connectedglass 1.1.7
	- continuity 3.0.0-beta.2+1.20
	- cooldown-coordinator 0.6.2
	- copperhopper 0.4.0+1.20.1
	- corgilib 4.0.0.0
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- creativecore 2.10.28
	   \-- net_minecraftforge_eventbus 6.0.3
	- creo 1.0.0-beta.21
	- crystals_overhauled 1.2.3
	- ctov 3.3.2
	- cull-less-leaves 1.2.0
	- dark-loading-screen 1.6.14
	- dawn 5.0.0
	   |-- cloth-config 11.0.99
	   |    \-- cloth-basic-math 0.6.1
	   |-- terraform-shapes-api-v1 7.0.1
	   \-- terraform-wood-api-v1 7.0.1
	- debugify 1.20.1+2.0
	- disenchanter 0.1.7+1.20
	- disintegratormod 1.0.4
	- doom 6.0.2
	- doubledoors 5.0
	- dualwield 4.0-1.20.1
	- durabilitytooltip 1.1.4
	- dynamiccrosshair 7.0.3+1.20
	   \-- yaclx 1.1+1.20
	- dynamiccrosshaircompat 3.2+1.20.1
	   \-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	- dynamicfps 2.4.0
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- easyanvils 8.0.0
	- easyhopper 2.6.2
	   \-- cloth-config 11.0.99
	        \-- cloth-basic-math 0.6.1
	- easymagic 8.0.0
	- enchantmentcompat 1.2.1
	- enchantmentsplus 1.1.7+1.20
	- entity_texture_features 4.4.4
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.2-mc1.20
	- extendedcopper 1.4.2
	- extra-damage-enchantments 1.1.0
	- fabric-api 0.86.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.62+df3654b377
	   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.2.0+6c31357e77
	   |-- fabric-dimensions-v1 2.1.52+b3afc78b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.9+132c48c177
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
	   |-- fabric-message-api-v1 5.1.7+3265161977
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.1+9386d8a777
	   |-- fabric-models-v0 0.4.0+9386d8a777
	   |-- fabric-networking-api-v1 1.3.9+b3afc78b77
	   |-- fabric-networking-v0 0.3.49+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.19+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.0+2e061fd477
	   |-- fabric-renderer-api-v1 3.1.1+9386d8a777
	   |-- fabric-renderer-indigo 1.4.1+9172968c77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.34+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.28+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.0+cdf060b277
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabric-language-kotlin 1.10.8+kotlin.1.9.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.21.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.2
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1
	- fabricloader 0.14.21
	- fallingleaves 1.15.2+1.20.1
	- fallingtree 4.2.1
	- faster_entity_animations 1.6
	- fastload 3.4.0
	   |-- conditional-mixin 0.3.2
	   |-- fastload-119-0-1-2-compat 3.4.0
	   |-- fastload-1193-compat 3.4.0
	   |-- fastload-1194-compat 3.4.0
	   \-- fastload_fapi_forward 1.0.2
	- ferritecore 6.0.0
	- fishofthieves 3.0.2
	- forbidden_potions 1.1.0
	- forgeconfigapiport 8.0.0
	- friendsandfoes 1.9.3
	- frogson 1.14.0.beta7
	- frozenlib 1.3.3-Fabric+1.20.1
	   |-- blue_endless_jankson 1.2.2
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.9
	- fullturtlearmor 1.5
	- fwaystones 3.1.2+mc1.20
	- geckolib 4.2.1
	- grindenchantments 3.1.2+1.20
	   \-- codec-config-api 1.0.2+1.19.3
	- halberd-multitool 4.1.2
	- illagersweararmor 1.1.0+1.20
	- immediatelyfast 1.1.16+1.20.1
	   \-- net_lenni0451_reflect 1.2.1
	- imst 2.1.0
	- imst_n 1.0.0
	- indium 1.0.21+mc1.20.1
	- infinitory 1.5.0-pre.4+1.20
	- inventoryprofilesnext 1.10.6
	- iris 1.6.4
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- jade 11.3.0
	- jamlib 0.6.0+1.20
	- java 19
	- knavesneeds 1.1.5+1.20.1
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lambdynlights 2.3.1+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- languagereload 1.5.8+1.20.1
	- libipn 3.0.2
	- lightoverlay 8.0.0
	- lithium 0.11.2
	- malilib 0.16.1
	- mca 7.5.3+1.20.1
	- mcpitanlibarch 1.7.5-1.20.1-fabric
	   \-- org_yaml_snakeyaml 2.0
	- memoryleakfix 1.1.1
	- midnightlib 1.4.1
	- mine_treasure_mr 1.2.9
	- minecraft 1.20.1
	- mixintrace 1.1.1+1.17
	- modernfix 5.3.1+mc1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.1+9386d8a777
	   \-- fabric-screen-api-v1 2.0.7+b3afc78b77
	- modmenu 7.2.1
	- moonlight 1.20-2.7.1
	- more_amethystrecipes_mr 1.0
	- morebows 1.0.11+1.20.x
	- moremobvariants 1.2.2
	- moreswordsmod 0.0.2-1.20.1
	- mr_dungeons_andtaverns 1-v2.1.4
	- mru 0.2.1+1.20
	- mutantmonsters 8.0.2
	   |-- cardinal-components-base 5.2.1
	   \-- cardinal-components-entity 5.2.1
	- mvs 4.0-1.20-fabric
	- mythicmetals 0.18.0+1.20
	   |-- additionalentityattributes 1.2.2+1.19.4
	   \-- common-protection-api 1.0.0
	- newworld 1.3.0
	   \-- terraform-wood-api-v1 7.0.1
	- no-shield-delay 1.0.0
	- obsidian_slab 1.2.0
	- omnihopper 2.1.0+1.20
	   \-- cicada 0.4.0
	- owo 0.11.1+1.20
	- philipsruins 1.20.1
	- ping-wheel 1.4.0
	- plentyofarmors 1.2.1
	- polymer-bundled 0.5.5+1.20.1
	   |-- polymer-autohost 0.5.5+1.20.1
	   |-- polymer-blocks 0.5.5+1.20.1
	   |-- polymer-common 0.5.5+1.20.1
	   |    \-- packet_tweaker 0.4.0+1.19.4
	   |-- polymer-core 0.5.5+1.20.1
	   |    |-- polymer-networking 0.5.5+1.20.1
	   |    |    \-- polymer-common 0.5.5+1.20.1
	   |    |         \-- packet_tweaker 0.4.0+1.19.4
	   |    \-- polymer-registry-sync-manipulator 0.5.5+1.20.1
	   |-- polymer-resource-pack 0.5.5+1.20.1
	   |    \-- polymer-common 0.5.5+1.20.1
	   |         \-- packet_tweaker 0.4.0+1.19.4
	   \-- polymer-virtual-entity 0.5.5+1.20.1
	        \-- polymer-common 0.5.5+1.20.1
	             \-- packet_tweaker 0.4.0+1.19.4
	- promenade 4.1.0
	- pumpeddesertfabric 1.0.0
	- puzzleslib 8.0.7
	- qu-enchantments 1.3.5-1.20
	   \-- mm 2.3
	- reeses-sodium-options 1.5.1+mc1.20-build.74
	- regions_unexplored 0.4.1+1.20.1
	- reinforced-upgrade 1.0.1-1.20.1
	- repurposed_structures 7.0.0+1.20-fabric
	- reputation 0.2.4+jade.1.20
	- rightclickharvest 3.2.2+1.19.x-1.20.1-fabric
	- roughlyenoughitems 12.0.634
	   \-- error_notifier 1.0.9
	- rrls 1.20.1-3.1.0-fabric
	- saplanting 1.2.4
	- satin 1.13.0
	- servercore 1.3.7+1.20.1
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- placeholder-api 2.1.1+1.20
	- showdurability 1.1.0+1.20.1
	- simplemango 1.3.2
	- simplyswords 1.48.1-1.21
	- skeletonhorsespawn 3.6
	- smartbrainlib 1.11
	- sodium 0.4.10+build.27
	- sodium-extra 0.4.23+mc1.20.1-build.106
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- sound_physics_remastered 1.20.1-1.1.1
	- spark 1.10.42
	- species 1.3-fabric
	- spellbound_weapons_mr 4.0.5f
	- spoornarmorattributes 3.0-1.20.1
	- spoornweaponattributes 5.0-1.20.1
	- stendhal 1.3.9-1.20
	   \-- libgui 8.0.0-beta.1+1.20-rc1
	        |-- jankson 5.0.1+j1.2.2
	        \-- libninepatch 1.2.0
	- strangeberries 2.2.1
	- subterrestrial 2.2.0
	- supermartijn642configlib 1.1.7
	- supermartijn642corelib 1.1.11
	- terrablender 3.0.0.169
	- terralith 2.4.2
	- terrestria 6.0.8
	   |-- biolith 1.0.0-alpha.8
	   |    \-- terraform-surfaces-api-v1 7.0.1
	   |-- terraform-biome-remapper-api-v1 7.0.1
	   |-- terraform-config-api-v1 7.0.1
	   |-- terraform-dirt-api-v1 7.0.1
	   |-- terraform-shapes-api-v1 7.0.1
	   |-- terraform-surfaces-api-v1 7.0.1
	   |-- terraform-tree-api-v1 7.0.1
	   |-- terraform-wood-api-v1 7.0.1
	   |-- terrestria-client 6.0.8
	   |-- terrestria-common 6.0.8
	   \-- terrestria-worldgen 6.0.8
	- toolstats 16.0.1
	- tooltipfix 1.1.1-1.20
	- tooltiprareness 1.0.9
	- travelersbackpack 1.20.1-9.1.2
	- traverse 7.0.8
	   |-- biolith 1.0.0-alpha.8
	   |    \-- terraform-surfaces-api-v1 7.0.1
	   |-- terraform-biome-remapper-api-v1 7.0.1
	   |-- terraform-config-api-v1 7.0.1
	   |-- terraform-surfaces-api-v1 7.0.1
	   |-- terraform-tree-api-v1 7.0.1
	   |-- terraform-wood-api-v1 7.0.1
	   |-- traverse-client 7.0.8
	   |-- traverse-common 7.0.8
	   \-- traverse-worldgen 7.0.8
	- treeharvester 8.2
	- trinkets 3.7.0
	- tropics 1.0.2
	- tweakermore 3.13.1
	- uncraftingtable76 1.2.6
	- universalenchants 8.0.0
	   |-- cardinal-components-base 5.2.1
	   |-- cardinal-components-entity 5.2.1
	   \-- extensibleenums 7.0.1
	- veinmining 1.2.0+1.20.1
	   \-- spectrelib 0.13.13+1.20.1
	- villagernames 5.2
	- villagersplus 1.11
	- visuality 0.7.0+1.20
	- voicechat 1.20.1-2.4.15
	- wi_zoom 1.4-MC1.20.1
	- woof 4.0.2+1.20.1
	- xaerominimap 23.5.0
	- xaeroworldmap 1.30.6
	- yet_another_config_lib_v3 3.0.3+1.20
	   |-- com_twelvemonkeys_common_common-image 3.9.4
	   |-- com_twelvemonkeys_common_common-io 3.9.4
	   |-- com_twelvemonkeys_common_common-lang 3.9.4
	   |-- com_twelvemonkeys_imageio_imageio-core 3.9.4
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.9.4
	   \-- com_twelvemonkeys_imageio_imageio-webp 3.9.4
	- zombiehorsespawn 4.6
```
Using `PolyMC version: 5.1`, `Java version 19.0.2, using 64 (amd64) architecture, from Azul Systems, Inc`,

A crash occur during startup:

```
[11:15:37] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) ~[NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) ~[NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) ~[NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) ~[NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) ~[NewLaunch.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 9 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1703 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 9 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method triggerSlotListeners(Lnet/minecraft/class_1799;IIZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;ZILnet/minecraft/class_1735;Lnet/minecraft/class_1799;)V in mixin/frozenlib.item.mixins.json:AbstractContainerMenuMixin from mod frozenlib failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.frozenlib.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 9 more
```
**Steps To Reproduce**
1. Install mods listed above
2. Start Minecraft
3. -
4. -

**Expected Behavior**
Normal startup expected.

**Screenshots**

**Logs**
[latest.log](https://github.com/FrozenBlock/FrozenLib/files/12120720/latest.log)

**Additional context**
The Minecraft starts normally with this mods set (when mod `FrozenLib` is excluded or deactivated).

I'm not sure is it a `FrozenLib` mod bug or other mod's bug or some incompatibility issues.

Thanks!

**Comment by lospejos** [comment]
After some additional research it seems that there is some mods compatibility issue.
When installed only `Wilder Wild` mod (which includes `FrozenLib` inside), this error not appears.
