### ISSUE TITLE
Can't Launch In Retail MC

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/FrozenLib#4]
Some stupid accesswidener issue.

**Comment by AViewFromTheTop** [comment]
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod frozenblocklib
at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
... 3 more

**Comment by MerpisMe** [comment]
accesswidener issue it seems
@Treetrain1

**Comment by AViewFromTheTop** [comment]
FrozenLib also complains about not finding the right method
I’m away atm, so can someone please revert this stuff and put the new Dripstone stuff back on WW?

**Comment by AViewFromTheTop** [comment]
yep it didn't instantly crash upon opening
Thank you @Treetrain1 !!
