### ISSUE TITLE
server block sound crash

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/FrozenLib#7]
29.11 22:43:23 [Server] INFO net.minecraft.class_148: Ticking entity
29.11 22:43:23 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
29.11 22:43:23 [Server] INFO at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
29.11 22:43:23 [Server] INFO at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
29.11 22:43:23 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
29.11 22:43:23 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
29.11 22:43:23 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
29.11 22:43:23 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.forEach(java.util.function.BiConsumer)" because "this.overwrites" is null
29.11 22:43:23 [Server] INFO at net.frozenblock.lib.sound.impl.block_sound_group.BlockSoundGroupManager.getOverwrites(BlockSoundGroupManager.java:66) ~[frozenlib-1.1.5-Fabric+1.19.2-unstable-5aa6ab586907aefa.jar:?]
29.11 22:43:23 [Server] INFO at net.frozenblock.lib.sound.api.block_sound_group.BlockSoundGroupOverwrites.getOverwrites(BlockSoundGroupOverwrites.java:44) ~[frozenlib-1.1.5-Fabric+1.19.2-unstable-5aa6ab586907aefa.jar:?]
29.11 22:43:23 [Server] INFO at net.minecraft.class_2248.handler$zlo000$getSoundGroupOverride(class_2248.java:1189) ~[server-intermediary.jar:?]

**Comment by AViewFromTheTop** [comment]
wait or is this a ww issue

**Comment by AViewFromTheTop** [comment]
it isnt

**Comment by AViewFromTheTop** [comment]
seems to be fixed now
